### ISSUE TITLE
[Bug] System throw an exception while running Goddess Service

### ISSUE THREAD

**Issue by huytrongnguyen** [huytrongnguyen/royal-road#26]
```
Unhandled Exception: System.InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RoyalRoad.Core.Stores.BaseStore`2.FindBy[TEntity](Func`2 predicate) in /Users/lionel/workspace/royal-road/src/RoyalRoad.Core/Stores/BaseStore.cs:line 33
   at RoyalRoad.AuroraService.Services.GoddessService.CreateNpc(PredefinedScript script) in /Users/lionel/workspace/royal-road/src/RoyalRoad.AuroraService/Services/LifeGoddessService.cs:line 14
   at RoyalRoad.AuroraService.Services.GoddessService.ExecutePredefinedScript(PredefinedScript script) in /Users/lionel/workspace/royal-road/src/RoyalRoad.AuroraService/Services/GoddessService.cs:line 61
   at RoyalRoad.AuroraService.Services.GoddessService.<>c__DisplayClass15_1.<Execute>b__3(Int64 x) in /Users/lionel/workspace/royal-road/src/RoyalRoad.AuroraService/Services/GoddessService.cs:line 53
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Timer.TimerImpl.Tick(Int64 count)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass7_0`1.<SchedulePeriodic>b__1()
   at System.Reactive.Concurrency.AsyncLock.Wait(Action action)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by huytrongnguyen** [comment]
Need to investigate more, at this time, just try catch and log the exception to prevent system is stopped
